# -*- coding: utf-8 -*-
"""strategy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkNPMy3n-UpLhHK5VUmTsKDgLnq0eRNw
"""

import pandas as pd
import numpy as np

def run_momentum_strategy(monthly_price,
                          monthly_return,
                          monthly_liquidity,
                          mom_window=6,
                          top_pct=0.1,
                          liquidity_n=200):

    momentum = monthly_price.pct_change(mom_window, fill_method=None)

    portfolio_returns = []
    dates = monthly_return.index[mom_window:-1]

    for date in dates:

        liquid = (
            monthly_liquidity.loc[date]
            .dropna()
            .sort_values(ascending=False)
            .head(liquidity_n)
            .index
        )

        mom = momentum.loc[date, liquid].dropna()

        if len(mom) == 0:
            portfolio_returns.append(np.nan)
            continue

        selected = (
            mom.sort_values(ascending=False)
            .head(int(len(mom) * top_pct))
            .index
        )

        next_ret = monthly_return.shift(-1).loc[date, selected].dropna()

        if len(next_ret) == 0:
            portfolio_returns.append(np.nan)
        else:
            portfolio_returns.append(next_ret.mean())

    strategy = pd.Series(portfolio_returns, index=dates)

    return strategy